// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxlporyctojufbcwazqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bHBvcnljdG9qdWZiY3dhenF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjU4NTEsImV4cCI6MjA3MTcwMTg1MX0.5n_rDIiJyv3Kh2_uGvtSI6MhFmjtV6WKr-X9pVOLyTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});